repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v2.6.0"
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args: ["--config", "./setup.cfg"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
      - id: gitlint
        args: [ "--msg-filename" ]
