name: Test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt -r requirements.dev.txt
      - name: Lint with flake8
        uses: suo/flake8-github-action@v1
      - name: Test with pytest
        run: |
          pytest
      - name: Save coverage.xml
        uses: actions/upload-artifact@v2
        with:
          name: coverage-output
          path: coverage.xml
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Read coverage.xml
        uses: actions/download-artifact@v3
        with:
          name: coverage-output
      - name: Update readme coverage
        if: always()
        run: |
          make update-coverage
      - name: Commit readme file
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update readme coverage
          commit_options: "--no-verify"
          file_pattern: "README.md"
